In [2]:
cd ..

/teamspace/studios/this_studio/recsys2025

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [15]:
from pathlib import Path
import numpy as np
from enum import Enum
from typing import Dict, List
from data_utils.utils import (
    load_with_properties
)
from data_utils.data_dir import DataDir

In [16]:
class EventTypes(str, Enum):
    PRODUCT_BUY = "product_buy"
    SEARCH_QUERY = "search_query"
    ADD_TO_CART = "add_to_cart"
    REMOVE_FROM_CART = "remove_from_cart"
    PAGE_VISIT = "page_visit"


EVENT_TYPE_TO_COLUMNS: Dict[EventTypes, List[str]] = {
    EventTypes.PRODUCT_BUY: ["sku", "category", "price"],
    EventTypes.ADD_TO_CART: ["sku", "category", "price"],
    EventTypes.REMOVE_FROM_CART: ["sku", "category", "price"],
    EventTypes.PAGE_VISIT: ["url"],
    EventTypes.SEARCH_QUERY: [],
}
QUERY_COLUMN = "query"
EMBEDDINGS_DTYPE = np.float16

In [21]:
EventTypes.PRODUCT_BUY

In [17]:
EVENT_TYPE_TO_COLUMNS[EventTypes.PRODUCT_BUY]

['sku', 'category', 'price']

In [11]:
EVENT_TYPE_TO_COLUMNS

{<EventTypes.PRODUCT_BUY: 'product_buy'>: ['sku', 'category', 'price'],
 <EventTypes.ADD_TO_CART: 'add_to_cart'>: ['sku', 'category', 'price'],
 <EventTypes.REMOVE_FROM_CART: 'remove_from_cart'>: ['sku',
  'category',
  'price'],
 <EventTypes.PAGE_VISIT: 'page_visit'>: ['url'],
 <EventTypes.SEARCH_QUERY: 'search_query'>: []}

In [7]:
data_dir = "/teamspace/studios/this_studio/ubc_data"
data_dir = DataDir(Path(data_dir))

In [20]:
EVENT_TYPE_TO_COLUMNS

{<EventTypes.PRODUCT_BUY: 'product_buy'>: ['sku', 'category', 'price'],
 <EventTypes.ADD_TO_CART: 'add_to_cart'>: ['sku', 'category', 'price'],
 <EventTypes.REMOVE_FROM_CART: 'remove_from_cart'>: ['sku',
  'category',
  'price'],
 <EventTypes.PAGE_VISIT: 'page_visit'>: ['url'],
 <EventTypes.SEARCH_QUERY: 'search_query'>: []}

In [38]:
def load_relevant_clients_ids(input_dir: Path) -> np.ndarray:
    return np.load(input_dir / "relevant_clients.npy")

In [22]:
event_product_buy_df = load_with_properties(data_dir=data_dir, event_type=EventTypes.PRODUCT_BUY.value)

In [25]:
event_product_buy_df

,client_id,timestamp,sku,category,price,name
0,17649961,2022-07-23 20:15:25,18485,5492,72,[187 47 120 237 234 172 91 172 67 153 32 ...
1,16696114,2022-07-11 16:31:30,81192,6519,99,[241 241 241 241 241 241 241 241 112 241 241 2...
2,10238779,2022-05-29 19:35:40,510014,6350,58,[167 24 193 24 24 92 167 76 29 45 172 2...
3,10238779,2022-05-29 19:38:05,510014,6350,58,[167 24 193 24 24 92 167 76 29 45 172 2...
4,10238779,2022-05-29 19:38:05,510014,6350,58,[167 24 193 24 24 92 167 76 29 45 172 2...
...,...,...,...,...,...,...
1315056,7535041,2022-08-19 04:58:40,269962,2895,14,[128 159 53 89 131 143 53 171 53 214 141 1...
1315057,4284680,2022-08-22 20:48:45,368528,3147,94,[161 161 161 161 141 36 161 161 36 161 161 1...
1315058,4284680,2022-08-22 20:48:45,368528,3147,94,[161 161 161 161 141 36 161 161 36 161 161 1...
1315059,20304565,2022-09-02 12:38:50,79597,5349,0,[196 97 71 127 98 174 234 70 25 2 202 2...
1315060,20304565,2022-09-02 12:38:50,79597,5349,0,[196 97 71 127 98 174 234 70 25 2 202 2...

In [24]:
max_date = event_product_buy_df["timestamp"].max()
max_date

Timestamp('2022-09-12 23:58:35')

In [28]:
event_add_to_cart_df = load_with_properties(data_dir=data_dir, event_type=EventTypes.ADD_TO_CART.value)

In [31]:
event_add_to_cart_df

,client_id,timestamp,sku,category,price,name
0,17649961,2022-08-11 12:22:55,1398840,3263,11,[221 221 48 221 221 221 221 221 221 47 221 2...
1,315805,2022-09-11 05:34:10,1434568,1517,88,[ 43 139 41 3 29 198 174 210 211 68 13 1...
2,16696114,2022-07-11 16:27:00,81192,6519,99,[241 241 241 241 241 241 241 241 112 241 241 2...
3,6297287,2022-06-14 15:52:30,1070234,874,54,[ 18 18 18 18 18 18 18 18 18 18 18 ...
4,14462111,2022-07-14 12:52:50,1428777,3068,72,[107 155 249 129 127 85 188 214 98 191 193 1...
...,...,...,...,...,...,...
3959152,6947176,2022-09-02 12:41:10,119225,6486,75,[ 82 124 79 61 101 71 190 243 85 59 53 1...
3959153,3850845,2022-06-12 16:13:59,1461294,5750,54,[223 136 128 42 89 128 198 81 132 224 8 2...
3959154,12296853,2022-07-29 17:53:45,431834,1677,54,[ 58 79 90 37 238 232 122 107 250 235 35 2...
3959155,12296853,2022-08-09 16:16:15,108846,5937,14,[ 35 236 204 84 65 65 35 219 49 49 65 ...
3959156,12296853,2022-08-09 16:17:10,388840,5937,34,[ 35 236 137 236 53 255 242 219 49 242 65 ...

In [32]:
event_remove_from_cart_df = load_with_properties(data_dir=data_dir, event_type=EventTypes.REMOVE_FROM_CART.value)

In [33]:
event_remove_from_cart_df

,client_id,timestamp,sku,category,price,name
0,23390068,2022-07-03 21:37:25,364528,5620,96,[ 48 221 84 99 234 101 234 190 68 112 211 ...
1,6220048,2022-08-03 10:20:50,98227,6519,98,[241 241 241 241 241 241 241 241 241 241 241 2...
2,7621267,2022-06-16 16:24:35,1455655,4340,67,[ 64 25 185 64 108 223 121 131 49 58 58 1...
3,20041561,2022-08-31 09:25:55,967683,1,26,[236 234 191 81 250 105 105 195 191 105 121 1...
4,11590800,2022-08-31 11:18:45,669874,5378,77,[167 82 3 83 71 45 17 41 45 83 83 1...
...,...,...,...,...,...,...
1230866,10121866,2022-08-29 10:54:30,707421,2151,39,[129 156 221 29 209 166 209 125 208 195 184 1...
1230867,22099839,2022-09-02 12:52:15,138436,2611,2,[ 29 170 102 213 71 1 213 234 34 47 115 ...
1230868,22099839,2022-09-02 12:53:20,138436,2611,2,[ 29 170 102 213 71 1 213 234 34 47 115 ...
1230869,22099839,2022-09-02 13:01:00,138436,2611,2,[ 29 170 102 213 71 1 213 234 34 47 115 ...
1230870,20304565,2022-09-02 12:38:30,679048,6103,14,[ 69 108 69 143 20 189 193 212 29 69 115 2...

In [34]:
event_page_visit_df = load_with_properties(data_dir=data_dir, event_type=EventTypes.PAGE_VISIT.value)

In [37]:
max_date = event_page_visit_df["timestamp"].max()
max_date

Timestamp('2022-09-12 23:59:59')

In [39]:
relevant_client_ids = load_relevant_clients_ids(input_dir=data_dir.input_dir)

In [41]:
# To Filter events for Relevant clients example
event_page_visit_df = event_page_visit_df[event_page_visit_df["client_id"].isin(relevant_client_ids)]